// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWLHeBWlz3wgK3QtL85KQxQxkqDUQWfM',
    appId: '1:532009755673:web:0f78ced393b6fffa7cf688',
    messagingSenderId: '532009755673',
    projectId: 'fb-login-a2e0f',
    authDomain: 'fb-login-a2e0f.firebaseapp.com',
    storageBucket: 'fb-login-a2e0f.appspot.com',
    measurementId: 'G-L6VJCJNNE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqTiPiJoQgHlY5ohGontaqfCf7gYaJWE',
    appId: '1:532009755673:android:2f393f0483c007907cf688',
    messagingSenderId: '532009755673',
    projectId: 'fb-login-a2e0f',
    storageBucket: 'fb-login-a2e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TosBOGUMLGwzyZpcRTGdI2VvNt6Zec0',
    appId: '1:532009755673:ios:88b3740f43e238327cf688',
    messagingSenderId: '532009755673',
    projectId: 'fb-login-a2e0f',
    storageBucket: 'fb-login-a2e0f.appspot.com',
    iosClientId:
        '532009755673-opd2lpilopirbkkuktpbn6voiai2o7cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3TosBOGUMLGwzyZpcRTGdI2VvNt6Zec0',
    appId: '1:532009755673:ios:7a0ffd305fbe6d6f7cf688',
    messagingSenderId: '532009755673',
    projectId: 'fb-login-a2e0f',
    storageBucket: 'fb-login-a2e0f.appspot.com',
    iosClientId:
        '532009755673-ri6mpa9phv0l4v44o2rora6hcjgncuhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
